# Generated by Django 4.0.2 on 2022-03-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdetailpage',
            name='custom_title',
            field=models.CharField(blank=True, help_text='Overwrites the default title', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newslistingpage',
            name='custom_title',
            field=models.CharField(blank=True, help_text='Overwrites the default title', max_length=100, null=True),
        ),
    ]
