# Generated by Django 4.0.2 on 2022-03-01 22:25

from django.db import migrations
import streams.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsdetailpage_custom_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdetailpage',
            name='ingress',
            field=wagtail.core.fields.StreamField([('simple_richtext', streams.blocks.SimpleRichtextBlock(form_classname='simple-richtext'))], blank=True, null=True),
        ),
    ]
