# Generated by Django 4.0.2 on 2022-02-21 10:33

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepagecarouselimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarouselimages',
            name='image_subtitle',
            field=wagtail.core.fields.RichTextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagecarouselimages',
            name='image_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
