# Generated by Django 4.0.2 on 2022-02-21 10:40

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepagecarouselimages_image_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecarouselimages',
            name='image_subtitle',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
