# Generated by Django 4.0.2 on 2022-02-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subscripers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Epostadress', max_length=254)),
                ('full_name', models.CharField(max_length=100)),
            ],
        ),
    ]
