# Generated by Django 4.0.2 on 2022-02-27 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subscripers',
            new_name='Subscriber',
        ),
    ]
